// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDEyuUZ28BlbVwnx7b2VeL4sgREYDudMRg',
    appId: '1:117912574481:web:28face6f6722f3fb742fb0',
    messagingSenderId: '117912574481',
    projectId: 'red-cross-checklist',
    authDomain: 'red-cross-checklist.firebaseapp.com',
    storageBucket: 'red-cross-checklist.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBjfE7XBO03S5z10P9pJP5zspEM0mVMfOY',
    appId: '1:117912574481:android:8520390675277c82742fb0',
    messagingSenderId: '117912574481',
    projectId: 'red-cross-checklist',
    storageBucket: 'red-cross-checklist.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCClZNhlSTGxV0i6zSgFhBscEDWbBhFRqI',
    appId: '1:117912574481:ios:5b54c50ec9339526742fb0',
    messagingSenderId: '117912574481',
    projectId: 'red-cross-checklist',
    storageBucket: 'red-cross-checklist.firebasestorage.app',
    iosBundleId: 'com.example.fyp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCClZNhlSTGxV0i6zSgFhBscEDWbBhFRqI',
    appId: '1:117912574481:ios:5b54c50ec9339526742fb0',
    messagingSenderId: '117912574481',
    projectId: 'red-cross-checklist',
    storageBucket: 'red-cross-checklist.firebasestorage.app',
    iosBundleId: 'com.example.fyp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDEyuUZ28BlbVwnx7b2VeL4sgREYDudMRg',
    appId: '1:117912574481:web:3dcf7d3fcebca13b742fb0',
    messagingSenderId: '117912574481',
    projectId: 'red-cross-checklist',
    authDomain: 'red-cross-checklist.firebaseapp.com',
    storageBucket: 'red-cross-checklist.firebasestorage.app',
  );
}
